#!/bin/bash
#
# This script uploads android build to repositories defined in maven-push.gradle
# It also builds and uploads Kotlin docs

if [[ `uname` == "Darwin" ]]; then
    export BOOST_ROOT=$(brew --prefix boost)
fi

export ANDROID_HOME="$HOME/Library/Android/sdk"
pushd android
./gradlew clean build assembleRelease publish -Pversion="1.0.0"

echo "Android build uploaded"
popd # android

